version: "3.2"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6378:6379"
    env_file:
      - ./my_dotenv.env.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT_env
      - REDIS_PASSWORD
    command: >
      redis-server --requirepass PSSW
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
